var mongoose = require('mongoose');

// MORE will be added to this schema for things like comments, reviews BY
// the person who is implementing those features...

var labSchema = mongoose.Schema({
    // unique id is atomatically generated by mondo bd saved at _id
    labname: String, // every lab has a unique name
    department: String,
    university: String,
    specialization: String,
    description: String,
    address: String,
    ratings: [{
        from: String, // email
        rating: String
    }],
    image: {
        data: Buffer,
        contentType: String
    },
    admin_approve: String, //when you first create a lab ,super admin has to approve the lab request
    creation_date: String,
    admin_name: String, // admin email address
    admin_email: String, // this is the unique field to identify the admin user of the lab
    members: [{
        name: String,
        email: String
    }], // user emails of lab members aprroved by admin
    membership_requests: [{
        name: String,
        email: String
    }], // users to be aprroved by admin
    equipment: [{
        // equipment schema
        name: String, // microscope
        quantity: Number, // 1
        price_per_hour: String, // $0 = free
        booking: [{ //manage the booking of equipments in this lab
            dateY: Number, //year
            dateM: Number, //month
            dateD: Number, //day
            slot: [{
                booked: Boolean, //if the slot is booked or now
                bookedBy: String, //who (email) booked this slot
                quantityLeft: Number //how many copies of this equip are left
            }]
        }],
        numBookingSlots: String,
        numBookingDays: String,
        notes: String,
        comments: [{
            from: String,
            time: String,
            comment: String
        }],
        ratings: [{
            from: String,
            rating: String
        }],
        number_of_ratings: String,
        overall_rating: String,
        hidden: String // again, if true, then the equipment is for lab-use only....
    }],
    comments: [{
        from: String,
        time: String,
        comment: String
    }]
});

module.exports = mongoose.model('Lab', labSchema);
